name: Build Mod

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build mod
        run: gradle -p minecraft-bots/botfury-mod build
      - name: Upload jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: minecraft-bots/botfury-mod/build/libs/botfury-0.1.0.jar
          asset_name: botfury-0.1.0.jar
          asset_content_type: application/java-archive
